version: '3'
services:
  web:
    build: .
    ports:
      - "5000:8080"    
    links:      
      - db
      - redis
    depends_on :            
      - db      
      - redis
  redis:
    image: "redis:alpine"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres    
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1        
    ports:
      - 9200:9200    
  wait:
    image: waisbrot/wait
    links:
      - es
      - db
      - redis
    environment:
      - TARGETS=es:9200,db:5432,redis:6379