# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

      - image: circleci/postgres
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: root
      
      - image: redis

      - image: circleci/elasticsearch        
      
    working_directory: /go/src/github.com/juliardidev/go-ci
    steps:
      - checkout
      - setup_remote_docker: 
         docker_layer_caching: true 

      # specify any bash command here prefixed with `run: `            
      - run: 
          name: Install dep
          command: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: 
          name: Update vendor
          command: dep ensure -v --vendor-only
      - run: 
          name: Clone service repository
          command: git clone https://github.com/JuliardiDev/go-service.git && mv go-service ../
      - run: 
          name: Run go service
          command: go run ../go-service/main.go &
      - run:
          name: Test files 
          command: go test