# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

      - image: circleci/postgres
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: root
      
      - image: redis

      - image: levlaz/elasticsearch-docker-ci:5.1.1        
      
    working_directory: /go/src/github.com/juliardidev/go-ci
    steps:
      - checkout
      - setup_remote_docker: 
         docker_layer_caching: true 

      # specify any bash command here prefixed with `run: `      
      - run: 
          name: Expose elastic port
          command: docker run -p 9200:9200 -d elasticsearch-docker-ci:5.1.1
      - run: 
          name: Install dep
          command: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: 
          name: Update vendor
          command: dep ensure -v --vendor-only
      - run:
          name: Test files 
          command: go test